name: bump
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
      - develop
      - uat

permissions:
  contents: read
env:
  USER_NAME: davikawasaki
  USER_EMAIL: davishinjik@gmail.com

jobs:
  bump:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0

      - name: Set up Commitizen
        run: |
          pip install --upgrade pip wheel
          pip install 'commitizen >=4.4.1'

      - name: Set up user
        run: |
          # Set up the GitHub user and email as author for the release commit.
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git config --list --global

      - name: Create changelog and bump
        env:
          BASE: ${{ github.base_ref }}
        run: |
          npm i

          # Get affected projects using Nx
          echo "$BASE"

          COMMIT_HASH=$(git rev-parse @~)
          echo $COMMIT_HASH
          CHANGED_APPS=$(npx nx show projects --affected --base=$COMMIT_HASH --head=origin/$BASE | tr '\n' ',')

          echo "Changed projects: '$CHANGED_APPS'"

          # Set prerelease flag based on branch
          if [[ ${{ github.ref }} == "refs/heads/develop" ]]; then
            CZ_FLAGS="--prerelease alpha"
          elif [[ ${{ github.ref }} == "refs/heads/uat" ]]; then
            CZ_FLAGS="--prerelease rc"
          fi

          # shellcheck disable=SC2086
          # Commitizen bump
          if [[ "$CHANGED_APPS" == *"shared"* || "$CHANGED_APPS" == "a,b,c," ]]; then
            cz --config projects/a/.cz.json bump --yes ${CZ_FLAGS}
            cz --config projects/b/.cz.json bump --yes ${CZ_FLAGS}
            cz --config projects/c/.cz.json bump --yes ${CZ_FLAGS}
          elif [[ "$CHANGED_APPS" == *"a"* ]]; then
            cz --config projects/a/.cz.json bump --yes ${CZ_FLAGS}
          elif [[ "$CHANGED_APPS" == *"b"* ]]; then
            cz --config projects/b/.cz.json bump --yes ${CZ_FLAGS}
          elif [[ "$CHANGED_APPS" == *"c"* ]]; then
            cz --config projects/c/.cz.json bump --yes ${CZ_FLAGS}
          else
            echo 'No changes on applications. Not bumping...'
            exit 1
          fi

      # - name: Push the release
      #   run: |
      #     git push --no-verify
      #     git push --tags --no-verify
